# Generated by Django 3.1.7 on 2021-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210302_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
